### ISSUE TITLE
Support for Linux agents

### ISSUE THREAD

**Issue by dnperfors** [blackducksoftware/detect-ado#12]
I am trying to hook up detect in our build pipeline, but we are running on linux agents and I get the following message:
```
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
```

Is there any change that this task can run on Linux using PowerShell core?

**Comment by yelob** [comment]
Additionally, if you do run it with a windows build agent, you can't use the DockerInspector, as that ONLY runs on non-windows operating systems.
https://github.com/blackducksoftware/synopsys-detect/blob/394525e9d0ec51b3ecb90ed0d7a1fca4b09ebb9c/detectable/src/main/java/com/synopsys/integration/detectable/detectables/docker/DockerDetectable.java#L75

**Comment by taikuukaits** [comment]
We are planning on rewriting the extension so it works on all operating systems.

**Comment by bamandel** [comment]
We are working on a new release now that will support linux agents and should resolve these issues for you.
