### ISSUE TITLE
Provide an Option to override download of Detect JAR

### ISSUE THREAD

**Issue by chilleregeravi** [blackducksoftware/detect-ado#15]
Currently, the task always tries to download the JAR and if the download fails the task fails as well.
There should be an option to override the download of JAR>

**Comment by bamandel** [comment]
The next release will download the jar to the tool directory and use that jar going forward. Alternatively, you can download the jar yourself, put it in tool directory of your agent, and the script will use that jar (assuming the version of the jar you have and the detect version in the task configuration matches).
