### ISSUE TITLE
Missing support for detect 7 in a new matching version

### ISSUE THREAD

**Issue by ymccready** [blackducksoftware/detect-ado#26]
Hello,
BlackDuck Detect version 7.0.0 was released, but we cannot use it with the extension. 
(Unless I'm mistaken and there is a way?)

Release notes:
https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/642351242/Releases+Notes

Thanks

**Comment by tommarkosi** [comment]
7.1.0 is now out and with it .NET 5 support.

Add me to the list of people who hopes they are mistaken that 7.x can't be used in this ADO task.

**Comment by mgardi85** [comment]
With the task version as 'SynopsysDetectTask@6' and the DetectVersion as 7.1.0, I see the scan is being performed using the version specified. This should have been achievable using "latest' as detect version but unfortunately that does not work.

**Comment by eric-labelle** [comment]
Detect is now at version 7.3.0 and yet still no version 7 of the Azure Devops task for version 7..

**Comment by mgardi85** [comment]
The version of task support v7 of detect scanner.

**Comment by ymccready** [comment]
Yes, apparently the task has been updated and now supports 7.* but it looks like Synopsys is not checking these issues or engaging here. Still, thanks for updating.
